# Generated by Django 6.0.7 on 2026-09-13 19:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Prueba Gratuita'), ('active', 'Activa'), ('expired', 'Vencida'), ('suspended', 'Suspendida')], default='trial', max_length=20)),
                ('plan', models.CharField(choices=[('trial', 'Prueba (14 días)'), ('monthly', 'Plan Mensual ($10.000/mes)'), ('yearly', 'Plan Anual ($100.000/año)'), ('lifetime', 'Licencia Vitalicia')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial_used', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_payment_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Plan Mensual ($10.000/mes)'), ('yearly', 'Plan Anual ($100.000/año)')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('reference_code', models.CharField(blank=True, help_text='N° de comprobante / referencia de transferencia', max_length=255)),
                ('payer_notes', models.TextField(blank=True, help_text='Comentario o aclaración del cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas del administrador')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to='accounts.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
