# Generated by Django 6.0.7 on 2026-09-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de Pago de Mercado Pago', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='mp_preference_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de Preferencia de Checkout de Mercado Pago', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='mp_status',
            field=models.CharField(blank=True, help_text='Estado de la transacción en Mercado Pago', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='payment_method',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago (Automático)'), ('manual_transfer', 'Transferencia Bancaria Manual')], default='mercadopago', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos crudos del Webhook / Respuesta de MP'),
        ),
    ]
