# Generated by Django 6.0.7 on 2026-09-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentnotification_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='basic_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento de funciones Básicas', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento de funciones Premium', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('trial', 'Prueba (Acceso Total)'), ('basic', 'Plan Básico'), ('premium', 'Plan Premium')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='plan',
            field=models.CharField(choices=[('basic_monthly', 'Plan Básico Mensual ($10.000/mes)'), ('basic_yearly', 'Plan Básico Anual ($100.000/año)'), ('premium_monthly', 'Plan Premium Mensual ($20.000/mes)'), ('premium_yearly', 'Plan Premium Anual ($200.000/año)'), ('monthly', 'Plan Básico Mensual ($10.000/mes)'), ('yearly', 'Plan Básico Anual ($100.000/año)')], default='basic_monthly', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento general del servicio', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Prueba (14 días)'), ('basic_monthly', 'Plan Básico Mensual ($10.000/mes)'), ('basic_yearly', 'Plan Básico Anual ($100.000/año)'), ('premium_monthly', 'Plan Premium Mensual ($20.000/mes)'), ('premium_yearly', 'Plan Premium Anual ($200.000/año)'), ('lifetime', 'Licencia Vitalicia Premium'), ('monthly', 'Plan Mensual ($10.000/mes)'), ('yearly', 'Plan Anual ($100.000/año)')], default='trial', max_length=30),
        ),
    ]
