# Generated by Django 6.0.7 on 2026-09-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_basic_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='plan',
            field=models.CharField(choices=[('basic_monthly', 'Plan Básico Mensual ($9.900/mes)'), ('basic_yearly', 'Plan Básico Anual ($99.000/año)'), ('premium_monthly', 'Plan Premium Mensual ($19.900/mes)'), ('premium_yearly', 'Plan Premium Anual ($199.000/año)'), ('monthly', 'Plan Básico Mensual ($9.900/mes)'), ('yearly', 'Plan Básico Anual ($99.000/año)')], default='basic_monthly', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Prueba (14 días)'), ('basic_monthly', 'Plan Básico Mensual ($9.900/mes)'), ('basic_yearly', 'Plan Básico Anual ($99.000/año)'), ('premium_monthly', 'Plan Premium Mensual ($19.900/mes)'), ('premium_yearly', 'Plan Premium Anual ($199.000/año)'), ('lifetime', 'Licencia Vitalicia Premium'), ('monthly', 'Plan Mensual ($9.900/mes)'), ('yearly', 'Plan Anual ($99.000/año)')], default='trial', max_length=30),
        ),
    ]
