# Generated by Django 6.0.7 on 2026-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemannouncement',
            name='auto_dismiss_on_reload',
            field=models.BooleanField(default=True, help_text='Se oculta automáticamente en el navegador una vez que el usuario recarga la página'),
        ),
    ]
