# Generated by Django 6.0.7 on 2026-09-29 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemannouncement_auto_dismiss_on_reload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Error / Falla técnica'), ('suggestion', 'Sugerencia o Mejora'), ('inquiry', 'Consulta o Pregunta')], default='suggestion', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, help_text='URL o sección donde se originó el reporte', max_length=255)),
                ('device_info', models.CharField(blank=True, help_text='Modo de dispositivo, resolución o navegador', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('resolved', 'Resuelto / Implementado'), ('dismissed', 'Descartado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas del administrador')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
