# Generated by Django 6.0.7 on 2026-08-22 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('user',), name='one_open_register_per_user'),
        ),
    ]
