# Generated by Django 6.0.7 on 2026-08-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_register_one_open_register_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionamount',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
