# Generated by Django 6.0.7 on 2026-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_transactionamount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, choices=[('sube', 'SUBE'), ('phone', 'Carga de celular'), ('virtual_cash', 'Cambio virtual/cash')], max_length=30, null=True),
        ),
    ]
