# Generated by Django 6.0.7 on 2026-08-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_provider_remove_client_unique_client_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('sale', 'Venta'), ('sube', 'Carga SUBE'), ('phone', 'Carga de celular'), ('exchange', 'Cambio'), ('sale_exchange', 'Venta + Cambio'), ('provider', 'Proveedor'), ('provider_payment', 'Pago a proveedor'), ('expense', 'Gasto'), ('loss', 'Pérdida'), ('payment', 'Pago de fiado')], max_length=30),
        ),
    ]
