# Generated by Django 6.0.7 on 2026-08-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.CreateModel(
            name='TransactionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Venta'), ('sube', 'Carga SUBE'), ('phone', 'Carga de celular'), ('exchange', 'Cambio'), ('payment', 'Pago de fiado'), ('provider', 'Proveedor'), ('provider_payment', 'Pago a proveedor'), ('expense', 'Gasto'), ('loss', 'Pérdida')], max_length=30)),
                ('service_type', models.CharField(blank=True, choices=[('sube', 'SUBE'), ('phone', 'Carga de celular'), ('virtual_cash', 'Cambio virtual/cash')], max_length=30, null=True)),
                ('exchange_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('exchange_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_operations', to='business.client')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_operations', to='business.provider')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='business.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOperationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('debt', 'Fiado')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('received', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='business.transactionoperation')),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionAmount',
        ),
    ]
