# Generated by Django 6.0.7 on 2026-08-29 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_move_client_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='initial_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
