# Generated by Django 6.0.7 on 2026-09-01 01:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_client_initial_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='initial_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='register',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
