# Generated by Django 6.0.7 on 2026-09-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_register_initial_bank_register_initial_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoperationamount',
            name='received',
            field=models.BooleanField(default=True),
        ),
    ]
