# Generated by Django 6.0.7 on 2026-09-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_transactionoperationamount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoperationamount',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
