# Generated by Django 6.0.7 on 2026-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_category_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo (kg)'), ('100g', '100 Gramos (100g)')], default='unit', max_length=10),
        ),
    ]
