# Generated by Django 6.0.7 on 2026-09-07 19:38

from django.db import migrations, models


def set_default_min_stock(apps, schema_editor):
    Product = apps.get_model('business', 'Product')
    Product.objects.filter(models.Q(min_stock=0) | models.Q(min_stock__isnull=True)).update(min_stock=1)


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_stockmovement_stocknote_transactionoperationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.RunPython(set_default_min_stock, migrations.RunPython.noop),
    ]

