# Generated by Django 6.0.7 on 2026-09-13 19:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_product_min_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Mi Negocio', help_text='Nombre del comercio o local', max_length=150)),
                ('store_address', models.CharField(blank=True, help_text='Dirección física del local (para tickets)', max_length=255)),
                ('store_phone', models.CharField(blank=True, help_text='Teléfono de contacto (para tickets)', max_length=50)),
                ('ticket_footer', models.CharField(blank=True, default='¡Gracias por su compra!', help_text='Mensaje al pie del ticket térmico', max_length=255)),
                ('exchange_fee_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($)')], default='percentage', max_length=20)),
                ('exchange_fee_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('phone_fee_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($)')], default='percentage', max_length=20)),
                ('phone_fee_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('sube_fee_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($)')], default='percentage', max_length=20)),
                ('sube_fee_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('debt_surcharge_enabled', models.BooleanField(default=False, help_text='Indica si se aplica recargo al vender fiado / en libreta')),
                ('debt_surcharge_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($)')], default='percentage', max_length=20)),
                ('debt_surcharge_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('is_setup_completed', models.BooleanField(default=False, help_text='True si el usuario ya completó el asistente inicial de configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Comercio',
                'verbose_name_plural': 'Configuraciones de Comercios',
            },
        ),
    ]
