# Generated by Django 6.0.7 on 2026-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('category_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('unit_type', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo (kg)'), ('100g', '100 Gramos (100g)')], default='unit', max_length=10)),
                ('suggested_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(default='sepa', help_text='Data source: sepa, gs1, openfoodfacts, manual, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto del Catálogo Maestro',
                'verbose_name_plural': 'Catálogo Maestro de Productos Nacionales',
                'indexes': [models.Index(fields=['barcode'], name='business_ma_barcode_79c0a8_idx'), models.Index(fields=['name'], name='business_ma_name_c3ac96_idx'), models.Index(fields=['brand'], name='business_ma_brand_02be70_idx')],
            },
        ),
    ]
