# Generated by Django on 2026-09-15

from django.db import migrations

CATEGORY_MAP = {
    "Gaseosas & Aguas Saborizadas": "Bebidas",
    "Jugos & Energizantes": "Bebidas",
    "Cervezas & Alcohol": "Bebidas",
    "Alfajores, Chocolates & Golosinas": "Golosinas & Snacks",
    "Snacks & Galletitas de Kiosco": "Golosinas & Snacks",
    "Yerba Mate, Té & Café": "Almacén",
    "Aceites, Harinas & Pastas Secas": "Almacén",
    "Conservas, Salsas & Condimentos": "Almacén",
    "Quesos (por peso y fraccionados)": "Fiambrería & Lácteos",
    "Fiambres & Embutidos": "Fiambrería & Lácteos",
    "Lácteos, Manteca & Tapas Frescas": "Fiambrería & Lácteos",
    "Verdulería & Hortalizas (por kilo)": "Verdulería & Frutería",
    "Frutería (por kilo)": "Verdulería & Frutería",
    "Panificados & Bollería": "Panadería",
    "Confitería & Sándwiches de Miga": "Panadería",
    "Cortes Vacunos (por kilo)": "Carnicería & Granja",
    "Pollería, Cerdo & Huevos": "Carnicería & Granja",
    "Limpieza del Hogar & Lavandería": "Limpieza",
    "Perfumería & Cuidado Personal": "Perfumería & Higiene",
    "Cigarrillos & Tabaquería": "Cigarrillos & Tabaquería",
    "Alimentos para Perros & Gatos": "Mascotas",
}


def consolidate_categories(apps, schema_editor):
    Category = apps.get_model('business', 'Category')
    Product = apps.get_model('business', 'Product')
    MasterCatalogProduct = apps.get_model('business', 'MasterCatalogProduct')

    # Re-map existing categories per user
    for old_name, new_name in CATEGORY_MAP.items():
        if old_name == new_name:
            continue
        old_cats = Category.objects.filter(name=old_name)
        for old_cat in old_cats:
            user = old_cat.user
            new_cat, _ = Category.objects.get_or_create(user=user, name=new_name)
            Product.objects.filter(category=old_cat).update(category=new_cat)
            old_cat.delete()

    # Re-map MasterCatalogProduct category names
    for old_name, new_name in CATEGORY_MAP.items():
        if old_name != new_name:
            MasterCatalogProduct.objects.filter(category_name=old_name).update(category_name=new_name)


def reverse_consolidation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_product_is_bundle_product_promo_price_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_categories, reverse_consolidation),
    ]

