# Generated by Django on 2026-09-15

from django.db import migrations


def consolidate_bread(apps, schema_editor):
    Product = apps.get_model('business', 'Product')

    old_names = [
        "Pan Francés / Baguette (por kg)",
        "Pan Criollo / Mignon (por kg)",
        "Pan Flauta / Felipe (por kg)",
    ]

    prods = Product.objects.filter(name__in=old_names)
    user_ids = set(p.user_id for p in prods if p.user_id)

    for user_id in user_ids:
        user_breads = Product.objects.filter(user_id=user_id, name__in=old_names)
        existing_generic = Product.objects.filter(user_id=user_id, name="Pan (por kg)").first()

        if not existing_generic and user_breads.exists():
            first_bread = user_breads.first()
            first_bread.name = "Pan (por kg)"
            first_bread.save(update_fields=['name'])
            user_breads.exclude(id=first_bread.id).delete()
        elif existing_generic:
            user_breads.exclude(id=existing_generic.id).delete()


def reverse_bread(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_consolidate_generalist_categories'),
    ]

    operations = [
        migrations.RunPython(consolidate_bread, reverse_bread),
    ]

