# Generated by Django 6.0.7 on 2026-09-16 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_consolidate_bread_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='card_surcharge_enabled',
            field=models.BooleanField(default=False, help_text='Indica si se aplica recargo al cobrar con tarjeta (débito/crédito)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='card_surcharge_type',
            field=models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto Fijo ($)')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='card_surcharge_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
    ]
