# Generated by Django 6.0.7 on 2026-09-17 00:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_storesettings_card_surcharge_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la cuenta o billetera (ej. Mercado Pago, Cuenta DNI, Banco Galicia)', max_length=100)),
                ('account_type', models.CharField(choices=[('virtual_wallet', 'Billetera Virtual'), ('bank', 'Cuenta Bancaria')], default='virtual_wallet', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Indica si es la cuenta predeterminada para transferencias y tarjetas')),
                ('is_active', models.BooleanField(default=True)),
                ('cbu_cvu', models.CharField(blank=True, default='', max_length=30)),
                ('alias', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transactionoperationamount',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_amounts', to='business.bankaccount'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_bank_account_name_per_user_ci'),
        ),
    ]
