# Generated by Django 6.0.7 on 2026-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_bankaccount_transactionoperationamount_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Límite personalizado de fiado ($). Si es nulo, se utiliza el límite general del comercio.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='global_debt_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Límite máximo general de fiado para clientes ($). Dejar vacío si no hay límite.', max_digits=12, null=True),
        ),
    ]
