# Generated by Django 6.0.7 on 2026-09-28 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_client_debt_limit_storesettings_global_debt_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo predeterminado de envío ($)', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='delivery_enabled',
            field=models.BooleanField(default=False, help_text='Indica si el local realiza envíos a domicilio / pedidos delivery'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_address',
            field=models.CharField(blank=True, default='', help_text='Dirección de entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del envío cobrado al cliente', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_notes',
            field=models.CharField(blank=True, default='', help_text='Notas o instrucciones para el repartidor / cadete', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('out_for_delivery', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_delivery',
            field=models.BooleanField(default=False, help_text='Indica si es un pedido con envío a domicilio'),
        ),
    ]
