# Generated by Django 6.0.7 on 2026-09-30 17:56

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_storesettings_default_delivery_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoperationamount',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('debt', 'Fiado'), ('employee', 'Consumo empleado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salary_type', models.CharField(choices=[('monthly', 'Mensual'), ('daily', 'Por día (jornal)'), ('hourly', 'Por hora'), ('fixed', 'Fijo / Por turno')], default='monthly', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario base pactado según la modalidad (mensual, jornal diario, etc.)', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento para consumos internos en el local (ej. 15.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el empleado está actualmente activo en el comercio')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Empleado / Cajero que realizó la operación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='business.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Llegada tarde'), ('justified', 'Ausencia justificada'), ('day_off', 'Franco / Descanso')], default='present', max_length=20)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, default=Decimal('8.00'), max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='business.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consumption', 'Consumo interno'), ('advance', 'Adelanto de sueldo'), ('bonus', 'Premio / Adicional'), ('deduction', 'Descuento / Sanción'), ('salary_payment', 'Pago de sueldo')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled', models.BooleanField(default=False, help_text='Indica si este movimiento ya fue incluido en una liquidación de sueldo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='business.employee')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_movements', to='business.transaction')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegisterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('initial_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efectivo en caja al iniciar el turno', max_digits=12)),
                ('declared_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado y declarado por el cajero al entregar el turno', max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo teórico calculado según las operaciones del turno', max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia de caja (declared_cash - expected_cash): positivo=sobrante, negativo=faltante', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observaciones de entrega o novedades del turno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='business.employee')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='business.register')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Turno de caja durante el cual se registró la operación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='business.registershift'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_employee_name_per_user_ci'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_per_date'),
        ),
    ]
