# Generated by Django 6.0.7 on 2026-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_alter_transactionoperationamount_method_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
