# Generated by Django 6.0.7 on 2026-09-30 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='business.employee'),
        ),
    ]
