# Generated by Django 6.0.7 on 2026-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_alter_registershift_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Indica si esta jornada ya fue incluida en una liquidación de sueldo'),
        ),
    ]
