# Generated by Django 6.0.7 on 2026-10-01 19:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_employeeattendance_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Perfil de empleado asociado para compras con descuento de personal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to='business.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje de descuento para compras del empleado en el local (ej. 10.00)', max_digits=5),
        ),
    ]
